# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieDiaryApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieDiaryApp
    pod 'Alamofire'
    pod 'Kingfisher'
    pod 'ObjectMapper'
    pod 'RealmSwift'

  target 'MovieDiaryAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieDiaryAppUITests' do
    # Pods for testing
  end

end
